@baseUrl = http://localhost:3001/api/v2

### Read all users
GET {{baseUrl}}/users

### Create a new user
POST {{baseUrl}}/users
Content-Type: application/json

{
  "username": "ADMINark1",
  "email": "saharadADmin@example.com",
  "password": "passAD321",
  "role":"admin"
}

###Update user by ID
PUT {{baseUrl}}/users/6aa25546711a574162ed7a97
Content-Type: application/json

{
    "username": "Nuttibeet",
    "email":"neeibut1@exmaple.com",
    "password":"pass123"
}


###delete user by ID
DELETE {{baseUrl}}/users/6a9ec578034e05693903dcc3

###delete all data
DELETE {{baseUrl}}/users



